/**
 * Pact Provider Verification
 *
 * Verifies that the GrubAPI provider honours the pact generated by the
 * GrubUI consumer tests. Requires the Next.js server to be running.
 *
 * Run: npm run test:pact:provider  (server must be up on API_BASE_URL)
 */

import path from 'path'
import { Verifier } from '@pact-foundation/pact'
import { testLogger } from '@/lib/logger'

const BASE_URL = process.env.API_BASE_URL || 'http://localhost:3000'

describe('Pact Provider Verification: GrubAPI', () => {
  it('honours all consumer pacts', async () => {
    testLogger.info({ baseUrl: BASE_URL }, 'starting pact provider verification')

    const output = await new Verifier({
      provider: 'GrubAPI',
      providerBaseUrl: BASE_URL,
      providerVersion: '1.0.0',
      pactUrls: [path.resolve(__dirname, '../../pacts/GrubUI-GrubAPI.json')],
      logLevel: 'warn',
      publishVerificationResult: false
    }).verifyProvider()

    testLogger.info('pact provider verification complete')
    expect(output).toBeTruthy()
  }, 30000)
})
